# 项目相关配置
superman:
  # 名称
  name: superman
  # 版本
  version: 4.2.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: C:/superman/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  port: 8069  # 服务器的HTTP端口，默认为80
  servlet:
    context-path: /   # 应用程序的访问路径
  tomcat:
    uri-encoding: utf-8 # tomcat的URI编码
    max-threads: 800 # tomcat最大线程数，默认为200
    min-spare-threads: 30 #tomcat启动初始化的线程数，默认值是10

#spring 配置
spring:
  thymeleaf:  #模板引擎
    mode: HTML
    encoding: UTF-8
    cache: true #缓存禁用
  messages:  # 资源信息
    basename:  static/i18n/messages
  profiles:
    active: datasource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB #单个文件大小，默认为1MB
      max-request-size: 20MB #设置总上传的文件大小
  devtools:
    restart:
      enabled: false #热部署开关
    # activiti 模块
    # 解决启动报错：class path resource [processes/] cannot be resolved to URL because it does not exist
  activiti:
    check-process-definitions: false
    # 检测身份信息表是否存在
    db-identity-used: false

# 日志配置
logging:
  level:
    com.superman: debug
    org.springframework: warn

# 用户配置
user:
  password:
    maxRetryCount: 5 # 密码错误{maxRetryCount}次锁定10分钟

# MyBatis
mybatis:
  type-aliases-package: com.superman.**.domain  # 搜索指定包别名
  mapperLocations: classpath*:mapper/**/*Mapper.xml # 配置mapper的扫描，找到所有的mapper.xml映射文件
  configLocation: classpath:mybatis/mybatis-config.xml # 加载全局的配置文件

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:  count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

